spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/medicamentosdb
    username: app_user
    password: Rds#2026Prod

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org.flywaydb: INFO
