name: Terraform - API Gateway

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

env:
  AWS_ACCOUNT_ID: "043391333434"
  TF_ACTION: "destroy" # apply or destroy
  AWS_REGION: "us-east-1"
  GITHUB_ROLE_NAME: "Github-Actions-Terraform-Role"

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/${{env.GITHUB_ROLE_NAME}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Build Lambda (Java)
        working-directory: lambda
        run: mvn clean package

      - name: Terraform Init
        run: terraform init

        # Check if API Gateway exists and set API_ID env variable
      - name: Get API Gateway ID by name
        if: env.TF_ACTION == 'destroy'
        run: |
          API_ID=$(aws apigatewayv2 get-apis \
            --region $AWS_REGION \
            --query "Items[?Name=='example-http-api'].ApiId" \
            --output text)
          
          if [ -z "$API_ID" ]; then
            echo "✅ API Gateway não existe na AWS"
            exit 0
          fi
          
          echo "⚠️ API Gateway encontrado: $API_ID"
          echo "API_ID=$API_ID" >> $GITHUB_ENV


        # import Api Gateway in state
      - name: Terraform Import API Gateway
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          terraform state list | grep aws_apigatewayv2_api.http_api \
          || terraform import aws_apigatewayv2_api.http_api $API_ID

        # validates the import to see if the api gateway is in state
      - name: Validate API Gateway in Terraform state
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          if terraform state list | grep -q aws_apigatewayv2_api.http_api; then
            echo "✅ API Gateway está presente no state do Terraform"
          else
            echo "❌ API Gateway NÃO está no state do Terraform"
            exit 1
          fi

        # import lambda in state
      - name: Terraform Import Lambda Function
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          if aws lambda get-function \
            --function-name example-lambda-function \
            --region $AWS_REGION > /dev/null 2>&1; then
          
            terraform state list | grep -q aws_lambda_function.helloworld \
            || terraform import aws_lambda_function.helloworld example-lambda-function
          
            echo "✅ Lambda importada com sucesso no state"
          else
            echo "⚠️ Lambda não existe na AWS, nada para importar"
          fi

        # validates the import to see if the lambda is in state
      - name: Validate Lambda Function in Terraform state
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          if terraform state list | grep -q aws_lambda_function.helloworld; then
            echo "✅ Lambda Function está presente no state do Terraform"
          else
            echo "❌ Lambda Function NÃO está no state do Terraform"
            exit 1
          fi

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply/Destroy
        working-directory: terraform
        run: terraform ${{env.TF_ACTION}} -auto-approve

        # validates the destroy by checking if the API Gateway still exists in AWS
      - name: Validate API Gateway is destroyed in AWS
        if: env.TF_ACTION == 'destroy'
        working-directory: terraform
        run: |
          if aws apigatewayv2 get-api \
            --api-id $API_ID \
            --region $AWS_REGION > /dev/null 2>&1; then
            echo "❌ API Gateway ainda EXISTE na AWS após o destroy"
            exit 1
          else
            echo "✅ API Gateway NÃO existe mais na AWS (destroy confirmado)"
          fi